[package]
name = "linux-wallpaperengine"
version = "0.1.0"
edition = "2024"

[dependencies]
depkg = "1.1.1"
indicatif = "0.18.3"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = {version = "1.0.149"}
wgpu = "28.0.0"
